### ISSUE TITLE
Struggling with the installation of PrimerMapper

### ISSUE THREAD

**Issue by Cowby** [dohalloran/PrimerMapper#1]
Hi Damien,

first of all thanks for providing PrimerMapper, that sounds like a really interesting tool for my purposes. I've downloaded all sources, the paper and the tutorial on how to install it on my system. 
But when I started to get it on a blank system i got struggled the way to get it run. All depedencies that are needed are facing some troubles when I tried to get them to my system. Maybe you could provide a more detailed instruction on how to get PrimerMapper to run on a vanilla windows or unix. 

If needed I could provide more info about where I'm struggling but I think it could be more helpful for the community on how you get it run and what is your desired way to get their.

Thanks and regards,

Dominik

**Comment by dohalloran** [comment]
Hi Dominik, 

Thanks for your interest in PrimerMapper. Do you have the dependencies installed? 
 i.e.  Tkx, Cwd, Bio::SeqIO, Bio::Graphics, Bio::SeqFeature::Generic, List::Util 'max', base 'Exporter'.
If you are using Windows - there is a video available with the paper that goes through step by step the installation of PrimerMapper (however, this is assuming that you have all the dependencies installed). If you are having problems with getting the dependencies installed, use the Perl package manager or if you have Linux Ubuntu OS available, it is really straight forward to install dependencies using the apt-get package manager - good luck!

**Comment by Cowby** [comment]
Hi Damien, 

thanks for the reply. Sorry for being unclear on which step I'm facing problems. Being a bioinformatician I'm very familiar with the installation of the perl modules on my unix machine (and it runs there), but I had to provide the installation for a windows machine, which was used in your video. But trying to install the dependencies from scratch at the machine, nearly every dependency failed in some tests and even a forced installation wasn't successful. Therefore I thought it would be idea to get an impression from you how I should install it the right way (obviously you were in the position to install it) and to get a more a detailed version of the installation guide (including the perl dependencies) for everyone else facing issues with the installation.

Thanks and regards,

Dominik

. Yes I saw the video

**Comment by dohalloran** [comment]
Which dependencies are not working for you? And which versions?  What is the error message

**Comment by Cowby** [comment]
I was able to install the BioPerl dependency using cpan force install (used ActivePerl 5.24 and BioPerl 1.6.924). But when I ran the test for PrimerMapper the Bio::Graphics module was missing, which I tried to force install via cpan. But the test for it failed because the DB_File dependency was missing. Trying to get that failed because the BerkeleyDB-Extension was not present, which indeed is present on the system. That was the point where I didn't get my hands on. Thanks for any advice or idea.

**Comment by dohalloran** [comment]
Sounds like you are having issues with Bio::Graphics rather than PrimerMapper. I can tell you that I used the latest version of Bio::Graphics and it works fine (2.39) on Windows 7 and Ubuntu 16.04 . You may want to open an issue with the author of that specific module

**Comment by Cowby** [comment]
Thanks for closing this question. Yes I know that already and I contacted them therefore, but I think as running your software seems not as easy as it should be (there are more people searching for help in the web), I think it should support the best-practices in software development and give a brief but exact introduction in how to install PrimerMapper. The intention of my question was to get at least that, but I think you're not willing to do that.
